CREATE TABLE Move (
	id VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
	generation_id INTEGER NOT NULL references Generation(id),
	type_id VARCHAR(255) NOT NULL references Type(id),
	category_id VARCHAR(255) NOT NULL references Category(id),
	power INTEGER,
	accuracy INTEGER,
	pp INTEGER,
	effect VARCHAR(255),
);
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Absorb', 1, 'Grass', 'Special', 20, 100, 25, 'User recovers half the HP inflicted on opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Acid', 1, 'Poison', 'Special', 40, 100, 30, 'May lower opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Acid Armor', 1, 'Poison', 'Status', NULL, NULL, 20, 'Sharply raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Agility', 1, 'Psychic', 'Status', NULL, NULL, 30, 'Sharply raises user''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Amnesia', 1, 'Psychic', 'Status', NULL, NULL, 20, 'Sharply raises user''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Aurora Beam', 1, 'Ice', 'Special', 65, 100, 20, 'May lower opponent''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Barrage', 1, 'Normal', 'Physical', 15, 85, 20, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Barrier', 1, 'Psychic', 'Status', NULL, NULL, 20, 'Sharply raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bide', 1, 'Normal', 'Physical', NULL, NULL, 10, 'User takes damage for two turns then strikes back double.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bind', 1, 'Normal', 'Physical', 15, 85, 20, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bite', 1, 'Dark', 'Physical', 60, 100, 25, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Blizzard', 1, 'Ice', 'Special', 110, 70, 5, 'May freeze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Body Slam', 1, 'Normal', 'Physical', 85, 100, 15, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bone Club', 1, 'Ground', 'Physical', 65, 85, 20, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bonemerang', 1, 'Ground', 'Physical', 50, 90, 10, 'Hits twice in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bubble', 1, 'Water', 'Special', 40, 100, 30, 'May lower opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bubble Beam', 1, 'Water', 'Special', 65, 100, 20, 'May lower opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Clamp', 1, 'Water', 'Physical', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Comet Punch', 1, 'Normal', 'Physical', 18, 85, 15, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Confuse Ray', 1, 'Ghost', 'Status', NULL, 100, 10, 'Confuses opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Confusion', 1, 'Psychic', 'Special', 50, 100, 25, 'May confuse opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Constrict', 1, 'Normal', 'Physical', 10, 100, 35, 'May lower opponent''s Speed by one stage.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Conversion', 1, 'Normal', 'Status', NULL, NULL, 30, 'Changes user''s type to that of its first move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Counter', 1, 'Fighting', 'Physical', NULL, 100, 20, 'When hit by a Physical Attack, user strikes back with 2x power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Crabhammer', 1, 'Water', 'Physical', 100, 90, 10, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Cut', 1, 'Normal', 'Physical', 50, 95, 30, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Defense Curl', 1, 'Normal', 'Status', NULL, NULL, 40, 'Raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dig', 1, 'Ground', 'Physical', 80, 100, 10, 'Digs underground on first turn, attacks on second. Can also escape from caves.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Disable', 1, 'Normal', 'Status', NULL, 100, 20, 'Opponent can''t use its last attack for a few turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dizzy Punch', 1, 'Normal', 'Physical', 70, 100, 10, 'May confuse opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Double Kick', 1, 'Fighting', 'Physical', 30, 100, 30, 'Hits twice in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Double Slap', 1, 'Normal', 'Physical', 15, 85, 10, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Double Team', 1, 'Normal', 'Status', NULL, NULL, 15, 'Raises user''s Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Double-Edge', 1, 'Normal', 'Physical', 120, 100, 15, 'User receives recoil damage.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dragon Rage', 1, 'Dragon', 'Special', NULL, 100, 10, 'Always inflicts 40 HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dream Eater', 1, 'Psychic', 'Special', 100, 100, 15, 'User recovers half the HP inflicted on a sleeping opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Drill Peck', 1, 'Flying', 'Physical', 80, 100, 20, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Earthquake', 1, 'Ground', 'Physical', 100, 100, 10, 'Power is doubled if opponent is underground from using Dig.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Egg Bomb', 1, 'Normal', 'Physical', 100, 75, 10, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ember', 1, 'Fire', 'Special', 40, 100, 25, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Explosion', 1, 'Normal', 'Physical', 250, 100, 5, 'User faints.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fire Blast', 1, 'Fire', 'Special', 110, 85, 5, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fire Punch', 1, 'Fire', 'Physical', 75, 100, 15, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fire Spin', 1, 'Fire', 'Special', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fissure', 1, 'Ground', 'Physical', NULL, 30, 5, 'One-Hit-KO, if it hits.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Flamethrower', 1, 'Fire', 'Special', 90, 100, 15, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Flash', 1, 'Normal', 'Status', NULL, 100, 20, 'Lowers opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fly', 1, 'Flying', 'Physical', 90, 95, 15, 'Flies up on first turn, attacks on second turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Focus Energy', 1, 'Normal', 'Status', NULL, NULL, 30, 'Increases critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fury Attack', 1, 'Normal', 'Physical', 15, 85, 20, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fury Swipes', 1, 'Normal', 'Physical', 18, 80, 15, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Glare', 1, 'Normal', 'Status', NULL, 100, 30, 'Paralyzes opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Growl', 1, 'Normal', 'Status', NULL, 100, 40, 'Lowers opponent''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Growth', 1, 'Normal', 'Status', NULL, NULL, 20, 'Raises user''s Attack and Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Guillotine', 1, 'Normal', 'Physical', NULL, 30, 5, 'One-Hit-KO, if it hits.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Gust', 1, 'Flying', 'Special', 40, 100, 35, 'Hits Pokémon using Fly/Bounce with double power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Harden', 1, 'Normal', 'Status', NULL, NULL, 30, 'Raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Haze', 1, 'Ice', 'Status', NULL, NULL, 30, 'Resets all stat changes.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Headbutt', 1, 'Normal', 'Physical', 70, 100, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('High Jump Kick', 1, 'Fighting', 'Physical', 130, 90, 10, 'If it misses, the user loses half their HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Horn Attack', 1, 'Normal', 'Physical', 65, 100, 25, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Horn Drill', 1, 'Normal', 'Physical', NULL, 30, 5, 'One-Hit-KO, if it hits.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hydro Pump', 1, 'Water', 'Special', 110, 80, 5, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hyper Beam', 1, 'Normal', 'Special', 150, 90, 5, 'User must recharge next turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hyper Fang', 1, 'Normal', 'Physical', 80, 90, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hypnosis', 1, 'Psychic', 'Status', NULL, 60, 20, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ice Beam', 1, 'Ice', 'Special', 90, 100, 10, 'May freeze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ice Punch', 1, 'Ice', 'Physical', 75, 100, 15, 'May freeze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Jump Kick', 1, 'Fighting', 'Physical', 100, 95, 10, 'If it misses, the user loses half their HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Karate Chop', 1, 'Fighting', 'Physical', 50, 100, 25, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Kinesis', 1, 'Psychic', 'Status', NULL, 80, 15, 'Lowers opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Leech Life', 1, 'Bug', 'Physical', 80, 100, 10, 'User recovers half the HP inflicted on opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Leech Seed', 1, 'Grass', 'Status', NULL, 90, 10, 'Drains HP from opponent each turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Leer', 1, 'Normal', 'Status', NULL, 100, 30, 'Lowers opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Lick', 1, 'Ghost', 'Physical', 30, 100, 30, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Light Screen', 1, 'Psychic', 'Status', NULL, NULL, 30, 'Halves damage from Special attacks for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Lovely Kiss', 1, 'Normal', 'Status', NULL, 75, 10, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Low Kick', 1, 'Fighting', 'Physical', NULL, 100, 20, 'The heavier the opponent, the stronger the attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Meditate', 1, 'Psychic', 'Status', NULL, NULL, 40, 'Raises user''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mega Drain', 1, 'Grass', 'Special', 40, 100, 15, 'User recovers half the HP inflicted on opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mega Kick', 1, 'Normal', 'Physical', 120, 75, 5, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mega Punch', 1, 'Normal', 'Physical', 80, 85, 20, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Metronome', 1, 'Normal', 'Status', NULL, NULL, 10, 'User performs almost any move in the game at random.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mimic', 1, 'Normal', 'Status', NULL, NULL, 10, 'Copies the opponent''s last move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Minimize', 1, 'Normal', 'Status', NULL, NULL, 10, 'Sharply raises user''s Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mirror Move', 1, 'Flying', 'Status', NULL, NULL, 20, 'User performs the opponent''s last move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mist', 1, 'Ice', 'Status', NULL, NULL, 30, 'User''s stats cannot be changed for a period of time.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Night Shade', 1, 'Ghost', 'Special', NULL, 100, 15, 'Inflicts damage equal to user''s level.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Pay Day', 1, 'Normal', 'Physical', 40, 100, 20, 'A small amount of money is gained after the battle resolves.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Peck', 1, 'Flying', 'Physical', 35, 100, 35, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Petal Dance', 1, 'Grass', 'Special', 120, 100, 10, 'User attacks for 2-3 turns but then becomes confused.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Pin Missile', 1, 'Bug', 'Physical', 25, 95, 20, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Poison Gas', 1, 'Poison', 'Status', NULL, 90, 40, 'Poisons opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Poison Powder', 1, 'Poison', 'Status', NULL, 75, 35, 'Poisons opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Poison Sting', 1, 'Poison', 'Physical', 15, 100, 35, 'May poison the opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Pound', 1, 'Normal', 'Physical', 40, 100, 35, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Psybeam', 1, 'Psychic', 'Special', 65, 100, 20, 'May confuse opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Psychic', 1, 'Psychic', 'Special', 90, 100, 10, 'May lower opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Psywave', 1, 'Psychic', 'Special', NULL, 100, 15, 'Inflicts damage 50-150% of user''s level.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Quick Attack', 1, 'Normal', 'Physical', 40, 100, 30, 'User attacks first.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rage', 1, 'Normal', 'Physical', 20, 100, 20, 'Raises user''s Attack when hit.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Razor Leaf', 1, 'Grass', 'Physical', 55, 95, 25, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Razor Wind', 1, 'Normal', 'Special', 80, 100, 10, 'Charges on first turn, attacks on second. High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Recover', 1, 'Normal', 'Status', NULL, NULL, 10, 'User recovers half its max HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Reflect', 1, 'Psychic', 'Status', NULL, NULL, 20, 'Halves damage from Physical attacks for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rest', 1, 'Psychic', 'Status', NULL, NULL, 10, 'User sleeps for 2 turns, but user is fully healed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Roar', 1, 'Normal', 'Status', NULL, NULL, 20, 'In battles, the opponent switches. In the wild, the Pokémon runs.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rock Slide', 1, 'Rock', 'Physical', 75, 90, 10, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rock Throw', 1, 'Rock', 'Physical', 50, 90, 15, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rolling Kick', 1, 'Fighting', 'Physical', 60, 85, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sand Attack', 1, 'Ground', 'Status', NULL, 100, 15, 'Lowers opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Scratch', 1, 'Normal', 'Physical', 40, 100, 35, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Screech', 1, 'Normal', 'Status', NULL, 85, 40, 'Sharply lowers opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Seismic Toss', 1, 'Fighting', 'Physical', NULL, 100, 20, 'Inflicts damage equal to user''s level.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Self-Destruct', 1, 'Normal', 'Physical', 200, 100, 5, 'User faints.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sharpen', 1, 'Normal', 'Status', NULL, NULL, 30, 'Raises user''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sing', 1, 'Normal', 'Status', NULL, 55, 15, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Skull Bash', 1, 'Normal', 'Physical', 130, 100, 10, 'Raises Defense on first turn, attacks on second.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sky Attack', 1, 'Flying', 'Physical', 140, 90, 5, 'Charges on first turn, attacks on second. May cause flinching. High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Slam', 1, 'Normal', 'Physical', 80, 75, 20, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Slash', 1, 'Normal', 'Physical', 70, 100, 20, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sleep Powder', 1, 'Grass', 'Status', NULL, 75, 15, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sludge', 1, 'Poison', 'Special', 65, 100, 20, 'May poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Smog', 1, 'Poison', 'Special', 30, 70, 20, 'May poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Smokescreen', 1, 'Normal', 'Status', NULL, 100, 20, 'Lowers opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Soft-Boiled', 1, 'Normal', 'Status', NULL, NULL, 10, 'User recovers half its max HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Solar Beam', 1, 'Grass', 'Special', 120, 100, 10, 'Charges on first turn, attacks on second.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sonic Boom', 1, 'Normal', 'Special', NULL, 90, 20, 'Always inflicts 20 HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spike Cannon', 1, 'Normal', 'Physical', 20, 100, 15, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Splash', 1, 'Normal', 'Status', NULL, NULL, 40, 'Doesn''t do ANYTHING.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spore', 1, 'Grass', 'Status', NULL, 100, 15, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Stomp', 1, 'Normal', 'Physical', 65, 100, 20, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Strength', 1, 'Normal', 'Physical', 80, 100, 15, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('String Shot', 1, 'Bug', 'Status', NULL, 95, 40, 'Sharply lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Struggle', 1, 'Normal', 'Physical', 50, NULL, NULL, 'Only usable when all PP are gone. Hurts the user.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Stun Spore', 1, 'Grass', 'Status', NULL, 75, 30, 'Paralyzes opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Submission', 1, 'Fighting', 'Physical', 80, 80, 20, 'User receives recoil damage.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Substitute', 1, 'Normal', 'Status', NULL, NULL, 10, 'Uses HP to creates a decoy that takes hits.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Super Fang', 1, 'Normal', 'Physical', NULL, 90, 10, 'Always takes off half of the opponent''s HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Supersonic', 1, 'Normal', 'Status', NULL, 55, 20, 'Confuses opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Surf', 1, 'Water', 'Special', 90, 100, 15, 'Hits all adjacent Pokémon.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Swift', 1, 'Normal', 'Special', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Swords Dance', 1, 'Normal', 'Status', NULL, NULL, 20, 'Sharply raises user''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Tackle', 1, 'Normal', 'Physical', 40, 100, 35, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Tail Whip', 1, 'Normal', 'Status', NULL, 100, 30, 'Lowers opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Take Down', 1, 'Normal', 'Physical', 90, 85, 20, 'User receives recoil damage.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Teleport', 1, 'Psychic', 'Status', NULL, NULL, 20, 'Allows user to flee wild battles; also warps player to last PokéCenter.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thrash', 1, 'Normal', 'Physical', 120, 100, 10, 'User attacks for 2-3 turns but then becomes confused.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thunder', 1, 'Electric', 'Special', 110, 70, 10, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thunder Punch', 1, 'Electric', 'Physical', 75, 100, 15, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thunder Shock', 1, 'Electric', 'Special', 40, 100, 30, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thunder Wave', 1, 'Electric', 'Status', NULL, 90, 20, 'Paralyzes opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thunderbolt', 1, 'Electric', 'Special', 90, 100, 15, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Toxic', 1, 'Poison', 'Status', NULL, 90, 10, 'Badly poisons opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Transform', 1, 'Normal', 'Status', NULL, NULL, 10, 'User takes on the form and attacks of the opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Tri Attack', 1, 'Normal', 'Special', 80, 100, 10, 'May paralyze, burn or freeze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Twineedle', 1, 'Bug', 'Physical', 25, 100, 20, 'Hits twice in one turn. May poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Vine Whip', 1, 'Grass', 'Physical', 45, 100, 25, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Vise Grip', 1, 'Normal', 'Physical', 55, 100, 30, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Water Gun', 1, 'Water', 'Special', 40, 100, 25, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Waterfall', 1, 'Water', 'Physical', 80, 100, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Whirlwind', 1, 'Normal', 'Status', NULL, NULL, 20, 'In battles, the opponent switches. In the wild, the Pokémon runs.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Wing Attack', 1, 'Flying', 'Physical', 60, 100, 35, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Withdraw', 1, 'Water', 'Status', NULL, NULL, 40, 'Raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Wrap', 1, 'Normal', 'Physical', 15, 90, 20, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Aeroblast', 2, 'Flying', 'Special', 100, 95, 5, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ancient Power', 2, 'Rock', 'Special', 60, 100, 5, 'May raise all user''s stats at once.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Attract', 2, 'Normal', 'Status', NULL, 100, 15, 'If opponent is the opposite gender, it''s less likely to attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Baton Pass', 2, 'Normal', 'Status', NULL, NULL, 40, 'User switches out and gives stat changes to the incoming Pokémon.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Beat Up', 2, 'Dark', 'Physical', NULL, 100, 10, 'Each Pokémon in your party attacks.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Belly Drum', 2, 'Normal', 'Status', NULL, NULL, 10, 'User loses 50% of its max HP, but Attack raises to maximum.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bone Rush', 2, 'Ground', 'Physical', 25, 90, 10, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Charm', 2, 'Normal', 'Status', NULL, 100, 20, 'Sharply lowers opponent''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Conversion 2', 2, 'Normal', 'Status', NULL, NULL, 30, 'User changes type to become resistant to opponent''s last move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Cotton Spore', 2, 'Grass', 'Status', NULL, 100, 40, 'Sharply lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Cross Chop', 2, 'Fighting', 'Physical', 100, 80, 5, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Crunch', 2, 'Dark', 'Physical', 80, 100, 15, 'May lower opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Curse', 2, 'Ghost', 'Status', NULL, NULL, 10, 'Ghosts lose 50% of max HP and curse the opponent; Non-Ghosts raise Attack, Defense and lower Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Destiny Bond', 2, 'Ghost', 'Status', NULL, NULL, 5, 'If the user faints, the opponent also faints.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Detect', 2, 'Fighting', 'Status', NULL, NULL, 5, 'Protects the user, but may fail if used consecutively.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dragon Breath', 2, 'Dragon', 'Special', 60, 100, 20, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dynamic Punch', 2, 'Fighting', 'Physical', 100, 50, 5, 'Confuses opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Encore', 2, 'Normal', 'Status', NULL, 100, 5, 'Forces opponent to keep using its last move for 3 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Endure', 2, 'Normal', 'Status', NULL, NULL, 10, 'Always left with at least 1 HP, but may fail if used consecutively.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Extreme Speed', 2, 'Normal', 'Physical', 80, 100, 5, 'User attacks first.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('False Swipe', 2, 'Normal', 'Physical', 40, 100, 40, 'Always leaves opponent with at least 1 HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Feint Attack', 2, 'Dark', 'Physical', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Flail', 2, 'Normal', 'Physical', NULL, 100, 15, 'The lower the user''s HP, the higher the power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Flame Wheel', 2, 'Fire', 'Physical', 60, 100, 25, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Foresight', 2, 'Normal', 'Status', NULL, NULL, 40, 'Resets opponent''s Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Frustration', 2, 'Normal', 'Physical', NULL, 100, 20, 'Power decreases with higher Friendship.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fury Cutter', 2, 'Bug', 'Physical', 40, 95, 20, 'Power increases each turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Future Sight', 2, 'Psychic', 'Special', 120, 100, 10, 'Damage occurs 2 turns later.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Giga Drain', 2, 'Grass', 'Special', 75, 100, 10, 'User recovers half the HP inflicted on opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Heal Bell', 2, 'Normal', 'Status', NULL, NULL, 5, 'Heals the user''s party''s status conditions.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hidden Power', 2, 'Normal', 'Special', 60, 100, 15, 'Type and power depends on user''s IVs.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Icy Wind', 2, 'Ice', 'Special', 55, 95, 15, 'Lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Iron Tail', 2, 'Steel', 'Physical', 100, 75, 15, 'May lower opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Lock-On', 2, 'Normal', 'Status', NULL, NULL, 5, 'User''s next attack is guaranteed to hit.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mach Punch', 2, 'Fighting', 'Physical', 40, 100, 30, 'User attacks first.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Magnitude', 2, 'Ground', 'Physical', NULL, 100, 30, 'Hits with random power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mean Look', 2, 'Normal', 'Status', NULL, NULL, 5, 'Opponent cannot flee or switch.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Megahorn', 2, 'Bug', 'Physical', 120, 85, 10, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Metal Claw', 2, 'Steel', 'Physical', 50, 95, 35, 'May raise user''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Milk Drink', 2, 'Normal', 'Status', NULL, NULL, 10, 'User recovers half its max HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mind Reader', 2, 'Normal', 'Status', NULL, NULL, 5, 'User''s next attack is guaranteed to hit.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mirror Coat', 2, 'Psychic', 'Special', NULL, 100, 20, 'When hit by a Special Attack, user strikes back with 2x power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Moonlight', 2, 'Normal', 'Status', NULL, NULL, 5, 'User recovers HP. Amount varies with the weather.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Morning Sun', 2, 'Normal', 'Status', NULL, NULL, 5, 'User recovers HP. Amount varies with the weather.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mud-Slap', 2, 'Ground', 'Special', 20, 100, 10, 'Lowers opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Nightmare', 2, 'Ghost', 'Status', NULL, 100, 15, 'The sleeping opponent loses 25% of its max HP each turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Octazooka', 2, 'Water', 'Special', 65, 85, 10, 'May lower opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Outrage', 2, 'Dragon', 'Physical', 120, 100, 10, 'User attacks for 2-3 turns but then becomes confused.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Pain Split', 2, 'Normal', 'Status', NULL, NULL, 20, 'The user''s and opponent''s HP becomes the average of both.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Perish Song', 2, 'Normal', 'Status', NULL, NULL, 5, 'Any Pokémon in play when this attack is used faints in 3 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Powder Snow', 2, 'Ice', 'Special', 40, 100, 25, 'May freeze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Present', 2, 'Normal', 'Physical', NULL, 90, 15, 'Either deals damage or heals.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Protect', 2, 'Normal', 'Status', NULL, NULL, 10, 'Protects the user, but may fail if used consecutively.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Psych Up', 2, 'Normal', 'Status', NULL, NULL, 10, 'Copies the opponent''s stat changes.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Pursuit', 2, 'Dark', 'Physical', 40, 100, 20, 'Double power if the opponent is switching out.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rain Dance', 2, 'Water', 'Status', NULL, NULL, 5, 'Makes it rain for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rapid Spin', 2, 'Normal', 'Physical', 50, 100, 40, 'Raises user''s Speed and removes entry hazards and trap move effects.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Return', 2, 'Normal', 'Physical', NULL, 100, 20, 'Power increases with higher Friendship.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Reversal', 2, 'Fighting', 'Physical', NULL, 100, 15, 'The lower the user''s HP, the higher the power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rock Smash', 2, 'Fighting', 'Physical', 40, 100, 15, 'May lower opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rollout', 2, 'Rock', 'Physical', 30, 90, 20, 'Doubles in power each turn for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sacred Fire', 2, 'Fire', 'Physical', 100, 95, 5, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Safeguard', 2, 'Normal', 'Status', NULL, NULL, 25, 'The user''s party is protected from status conditions.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sandstorm', 2, 'Rock', 'Status', NULL, NULL, 10, 'Creates a sandstorm for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Scary Face', 2, 'Normal', 'Status', NULL, 100, 10, 'Sharply lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Shadow Ball', 2, 'Ghost', 'Special', 80, 100, 15, 'May lower opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sketch', 2, 'Normal', 'Status', NULL, NULL, 1, 'Permanently copies the opponent''s last move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sleep Talk', 2, 'Normal', 'Status', NULL, NULL, 10, 'User performs one of its own moves while sleeping.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sludge Bomb', 2, 'Poison', 'Special', 90, 100, 10, 'May poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Snore', 2, 'Normal', 'Special', 50, 100, 15, 'Can only be used if asleep. May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spark', 2, 'Electric', 'Physical', 65, 100, 20, 'May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spider Web', 2, 'Bug', 'Status', NULL, NULL, 10, 'Opponent cannot escape/switch.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spikes', 2, 'Ground', 'Status', NULL, NULL, 20, 'Hurts opponents when they switch into battle.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spite', 2, 'Ghost', 'Status', NULL, 100, 10, 'The opponent''s last move loses 2-5 PP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Steel Wing', 2, 'Steel', 'Physical', 70, 90, 25, 'May raise user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sunny Day', 2, 'Fire', 'Status', NULL, NULL, 5, 'Makes it sunny for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Swagger', 2, 'Normal', 'Status', NULL, 85, 15, 'Opponent becomes confused, but its Attack is sharply raised.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sweet Kiss', 2, 'Normal', 'Status', NULL, 75, 10, 'Confuses opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sweet Scent', 2, 'Normal', 'Status', NULL, 100, 20, 'Lowers opponent''s Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Synthesis', 2, 'Grass', 'Status', NULL, NULL, 5, 'User recovers HP. Amount varies with the weather.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Thief', 2, 'Dark', 'Physical', 60, 100, 25, 'Also steals opponent''s held item.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Triple Kick', 2, 'Fighting', 'Physical', 10, 90, 10, 'Hits thrice in one turn at increasing power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Twister', 2, 'Dragon', 'Special', 40, 100, 20, 'May cause flinching. Hits Pokémon using Fly/Bounce with double power.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Vital Throw', 2, 'Fighting', 'Physical', 70, NULL, 10, 'User attacks last, but ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Whirlpool', 2, 'Water', 'Special', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Zap Cannon', 2, 'Electric', 'Special', 120, 50, 5, 'Paralyzes opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Aerial Ace', 3, 'Flying', 'Physical', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Air Cutter', 3, 'Flying', 'Special', 60, 95, 25, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Arm Thrust', 3, 'Fighting', 'Physical', 15, 100, 20, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Aromatherapy', 3, 'Grass', 'Status', NULL, NULL, 5, 'Cures all status problems in your party.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Assist', 3, 'Normal', 'Status', NULL, NULL, 20, 'User performs a move known by its allies at random.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Astonish', 3, 'Ghost', 'Physical', 30, 100, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Blast Burn', 3, 'Fire', 'Special', 150, 90, 5, 'User must recharge next turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Blaze Kick', 3, 'Fire', 'Physical', 85, 90, 10, 'High critical hit ratio. May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Block', 3, 'Normal', 'Status', NULL, NULL, 5, 'Opponent cannot flee or switch.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bounce', 3, 'Flying', 'Physical', 85, 85, 5, 'Springs up on first turn, attacks on second. May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Brick Break', 3, 'Fighting', 'Physical', 75, 100, 15, 'Breaks through Reflect and Light Screen barriers.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bulk Up', 3, 'Fighting', 'Status', NULL, NULL, 20, 'Raises user''s Attack and Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Bullet Seed', 3, 'Grass', 'Special', 25, 100, 30, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Calm Mind', 3, 'Psychic', 'Status', NULL, NULL, 20, 'Raises user''s Special Attack and Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Camouflage', 3, 'Normal', 'Status', NULL, NULL, 20, 'Changes user''s type according to the location.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Charge', 3, 'Electric', 'Status', NULL, NULL, 20, 'Raises user''s Special Defense and next Electric move''s power increases.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Cosmic Power', 3, 'Psychic', 'Status', NULL, NULL, 20, 'Raises user''s Defense and Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Covet', 3, 'Normal', 'Physical', 60, 100, 25, 'Opponent''s item is stolen by the user.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Crush Claw', 3, 'Normal', 'Physical', 75, 95, 10, 'May lower opponent''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dive', 3, 'Water', 'Physical', 80, 100, 10, 'Dives underwater on first turn, attacks on second turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Doom Desire', 3, 'Steel', 'Special', 140, 100, 5, 'Damage occurs 2 turns later.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dragon Claw', 3, 'Dragon', 'Physical', 80, 100, 15, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Dragon Dance', 3, 'Dragon', 'Status', NULL, NULL, 20, 'Raises user''s Attack and Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Endeavor', 3, 'Normal', 'Physical', NULL, 100, 5, 'Reduces opponent''s HP to same as user''s.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Eruption', 3, 'Fire', 'Special', 150, 100, 5, 'Stronger when the user''s HP is higher.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Extrasensory', 3, 'Psychic', 'Special', 80, 100, 20, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Facade', 3, 'Normal', 'Physical', 70, 100, 20, 'Power doubles if user is burned, poisoned, or paralyzed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fake Out', 3, 'Normal', 'Physical', 40, 100, 10, 'User attacks first, foe flinches. Only usable on first turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Fake Tears', 3, 'Dark', 'Status', NULL, 100, 20, 'Sharply lowers opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Feather Dance', 3, 'Flying', 'Status', NULL, 100, 15, 'Sharply lowers opponent''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Flatter', 3, 'Dark', 'Status', NULL, 100, 15, 'Confuses opponent, but raises its Special Attack by two stages.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Focus Punch', 3, 'Fighting', 'Physical', 150, 100, 20, 'If the user is hit before attacking, it flinches instead.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Follow Me', 3, 'Normal', 'Status', NULL, NULL, 20, 'In Double Battle, the user takes all the attacks.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Frenzy Plant', 3, 'Grass', 'Special', 150, 90, 5, 'User must recharge next turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Grass Whistle', 3, 'Grass', 'Status', NULL, 55, 15, 'Puts opponent to sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Grudge', 3, 'Ghost', 'Status', NULL, NULL, 5, 'If the users faints after using this move, the PP for the opponent''s last move is depleted.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hail', 3, 'Ice', 'Status', NULL, NULL, 10, 'Non-Ice types are damaged for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Heat Wave', 3, 'Fire', 'Special', 95, 90, 10, 'May burn opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Helping Hand', 3, 'Normal', 'Status', NULL, NULL, 20, 'In Double Battles, boosts the power of the partner''s move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Howl', 3, 'Normal', 'Status', NULL, NULL, 40, 'Raises Attack of allies.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hydro Cannon', 3, 'Water', 'Special', 150, 90, 5, 'User must recharge next turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Hyper Voice', 3, 'Normal', 'Special', 90, 100, 10, NULL); 
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ice Ball', 3, 'Ice', 'Physical', 30, 90, 20, 'Doubles in power each turn for 5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Icicle Spear', 3, 'Ice', 'Physical', 25, 100, 30, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Imprison', 3, 'Psychic', 'Status', NULL, NULL, 10, 'Opponent is unable to use moves that the user also knows.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Ingrain', 3, 'Grass', 'Status', NULL, NULL, 20, 'User restores HP each turn. User cannot escape/switch.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Iron Defense', 3, 'Steel', 'Status', NULL, NULL, 15, 'Sharply raises user''s Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Knock Off', 3, 'Dark', 'Physical', 65, 100, 20, 'Removes opponent''s held item for the rest of the battle.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Leaf Blade', 3, 'Grass', 'Physical', 90, 100, 15, 'High critical hit ratio.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Luster Purge', 3, 'Psychic', 'Special', 70, 100, 5, 'May lower opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Magic Coat', 3, 'Psychic', 'Status', NULL, NULL, 15, 'Reflects moves that cause status conditions back to the attacker.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Magical Leaf', 3, 'Grass', 'Special', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Memento', 3, 'Dark', 'Status', NULL, 100, 10, 'User faints, sharply lowers opponent''s Attack and Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Metal Sound', 3, 'Steel', 'Status', NULL, 85, 40, 'Sharply lowers opponent''s Special Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Meteor Mash', 3, 'Steel', 'Physical', 90, 90, 10, 'May raise user''s Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mist Ball', 3, 'Psychic', 'Special', 70, 100, 5, 'May lower opponent''s Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mud Shot', 3, 'Ground', 'Special', 55, 95, 15, 'Lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Mud Sport', 3, 'Ground', 'Status', NULL, NULL, 15, 'Weakens the power of Electric-type moves.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Muddy Water', 3, 'Water', 'Special', 90, 85, 10, 'May lower opponent''s Accuracy.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Nature Power', 3, 'Normal', 'Status', NULL, NULL, 20, 'Uses a certain move based on the current terrain.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Needle Arm', 3, 'Grass', 'Physical', 60, 100, 15, 'May cause flinching.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Odor Sleuth', 3, 'Normal', 'Status', NULL, NULL, 40, 'Resets opponent''s Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Overheat', 3, 'Fire', 'Special', 130, 90, 5, 'Sharply lowers user''s Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Poison Fang', 3, 'Poison', 'Physical', 50, 100, 15, 'May badly poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Poison Tail', 3, 'Poison', 'Physical', 50, 100, 25, 'High critical hit ratio. May poison opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Psycho Boost', 3, 'Psychic', 'Special', 140, 90, 5, 'Sharply lowers user''s Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Recycle', 3, 'Normal', 'Status', NULL, NULL, 10, 'User''s used hold item is restored.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Refresh', 3, 'Normal', 'Status', NULL, NULL, 20, 'Cures paralysis, poison, and burns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Revenge', 3, 'Fighting', 'Physical', 60, 100, 10, 'Power increases if user was hit first.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rock Blast', 3, 'Rock', 'Physical', 25, 90, 10, 'Hits 2-5 times in one turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Rock Tomb', 3, 'Rock', 'Physical', 60, 95, 15, 'Lowers opponent''s Speed.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Role Play', 3, 'Psychic', 'Status', NULL, NULL, 10, 'User copies the opponent''s Ability.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sand Tomb', 3, 'Ground', 'Physical', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Secret Power', 3, 'Normal', 'Physical', 70, 100, 20, 'Effects of the attack vary with the location.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Shadow Punch', 3, 'Ghost', 'Physical', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sheer Cold', 3, 'Ice', 'Special', NULL, 30, 5, 'One-Hit-KO, if it hits.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Shock Wave', 3, 'Electric', 'Special', 60, NULL, 20, 'Ignores Accuracy and Evasiveness.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Signal Beam', 3, 'Bug', 'Special', 75, 100, 15, 'May confuse opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Silver Wind', 3, 'Bug', 'Special', 60, 100, 5, 'May raise all stats of user at once.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Skill Swap', 3, 'Psychic', 'Status', NULL, NULL, 10, 'The user swaps Abilities with the opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Sky Uppercut', 3, 'Fighting', 'Physical', 85, 90, 15, 'Hits the opponent, even during Fly.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Slack Off', 3, 'Normal', 'Status', NULL, NULL, 10, 'User recovers half its max HP.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Smelling Salts', 3, 'Normal', 'Physical', 70, 100, 10, 'Power doubles if opponent is paralyzed, but cures it.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Snatch', 3, 'Dark', 'Status', NULL, NULL, 10, 'Steals the effects of the opponent''s next move.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Spit Up', 3, 'Normal', 'Special', NULL, 100, 10, 'Power depends on how many times the user performed Stockpile.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Stockpile', 3, 'Normal', 'Status', NULL, NULL, 20, 'Stores energy for use with Spit Up and Swallow.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Superpower', 3, 'Fighting', 'Physical', 120, 100, 5, 'Lowers user''s Attack and Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Swallow', 3, 'Normal', 'Status', NULL, NULL, 10, 'The more times the user has performed Stockpile, the more HP is recovered.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Tail Glow', 3, 'Bug', 'Status', NULL, NULL, 20, 'Drastically raises user''s Special Attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Taunt', 3, 'Dark', 'Status', NULL, 100, 20, 'Opponent can only use moves that attack.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Teeter Dance', 3, 'Normal', 'Status', NULL, 100, 20, 'Confuses all Pokémon.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Tickle', 3, 'Normal', 'Status', NULL, 100, 20, 'Lowers opponent''s Attack and Defense.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Torment', 3, 'Dark', 'Status', NULL, 100, 15, 'Opponent cannot use the same move in a row.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Trick', 3, 'Psychic', 'Status', NULL, 100, 10, 'Swaps held items with the opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Uproar', 3, 'Normal', 'Special', 90, 100, 10, 'User attacks for 3 turns and prevents sleep.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Volt Tackle', 3, 'Electric', 'Physical', 120, 100, 15, 'User receives recoil damage. May paralyze opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Water Pulse', 3, 'Water', 'Special', 60, 100, 20, 'May confuse opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Water Sport', 3, 'Water', 'Status', NULL, NULL, 15, 'Weakens the power of Fire-type moves.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Water Spout', 3, 'Water', 'Special', 150, 100, 5, 'The higher the user''s HP, the higher the damage caused.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Weather Ball', 3, 'Normal', 'Special', 50, 100, 10, 'Move''s power and type changes with the weather.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Will-O-Wisp', 3, 'Fire', 'Status', NULL, 85, 15, 'Burns opponent.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Wish', 3, 'Normal', 'Status', NULL, NULL, 10, 'The user recovers HP in the following turn.');
INSERT INTO Move (id, generation_id, type_id, category_id, power, accuracy, pp, effect) VALUES ('Yawn', 3, 'Normal', 'Status', NULL, NULL, 10, 'Puts opponent to sleep in the next turn.');